
### GoDataType
# @name authenticate
POST {{app-host}}/api/public/core/account/login
Content-Type: application/json

{
    "Password": "{{env-password}}",
    "User": "{{env-user}}"
}

@Authorization = Bearer {{authenticate.response.body.$.JWT}}

#############################################################

###
# @name LIST_ACTIVE_NavElementss
GET {{app-host}}/api/core/navigator/elements/active-records/role/ADM_GRL
Content-Type: application/json
Authorization: {{Authorization}}




###############################################################
###############################################################
# @name GET_BY_ID_NavElements
GET {{app-host}}/api/core/navigator/elements/element/MAIL
Content-Type: application/json
Authorization: {{Authorization}}

###
@ID = MAIL.X
@UpdatedAt = {{GET_BY_ID_NavElements.response.body.$.UpdatedAt}}

###
# @name INSERT_NavElements
POST {{app-host}}/api/core/navigator/elements/element
Content-Type: application/json
Authorization: {{Authorization}}

{
    "ID": "MAIL.X",
    "Name": "Mail X",
    "Description": "Mail X Templates",
    "Icon": "mail",
    "Order": 0,
    "URL": "#",
    "ParentID": "MAIL"
}


###
# @name EDIT_NavElements
PUT  {{app-host}}/api/core/navigator/elements/element
Content-Type: application/json
Authorization: {{Authorization}}

{
    "ID": "{{ID}}",
    "Name": "Mail",
    "Description": "Mail Templates.",
    "Icon": "mail",
    "Order": 0,
    "URL": "#",
    "Parent": "",
    "UpdatedAt": "{{UpdatedAt}}"
}


###
# @name VALIDATE_NavElements
PUT  {{app-host}}/api/core/navigator/elements/element/validate
Content-Type: application/json
Authorization: {{Authorization}}

{
    "ID": "{{ID}}",
    "UpdatedAt": "{{UpdatedAt}}"
}


###
# @name INVALIDATE_NavElements
PUT  {{app-host}}/api/core/navigator/elements/element/invalidate
Content-Type: application/json
Authorization: {{Authorization}}

{
    "ID": "{{ID}}",
    "UpdatedAt": "{{UpdatedAt}}"
}

###
# @name SOFT_DELETE_NavElements
PUT  {{app-host}}/api/core/navigator/elements/element/soft-delete
Content-Type: application/json
Authorization: {{Authorization}}

{
    "ID": "{{ID}}",
    "UpdatedAt": "{{UpdatedAt}}"
}

###
# @name HARD_DELETE_NavElements
PUT  {{app-host}}/api/core/navigator/elements/element/hard-delete
Content-Type: application/json
Authorization: {{Authorization}}

{
    "ID": "{{ID}}",
    "UpdatedAt": "{{UpdatedAt}}"
}



###
# @name ASSOCIATE_ROLE_NavElements
PUT  {{app-host}}/api/core/navigator/elements/element/associate-role
Content-Type: application/json
Authorization: {{Authorization}}

{
    "NavElementID": "MAIL.X",
    "RoleID": "ADM_GRL"
}



###
# @name DISSOCIATE_ROLE_NavElements
PUT  {{app-host}}/api/core/navigator/elements/element/dissociate-role
Content-Type: application/json
Authorization: {{Authorization}}

{
    "NavElementID": "MAIL.X",
    "RoleID": "ADM_GRL"
}

###
# @name UPSERT_navigator
POST  {{app-host}}/api/core/navigator/upsert
Content-Type: application/json
Authorization: {{Authorization}}

[{"ID":"EXAMPLE1","Name":"Dashboard","Description":"example page","Icon":"dashboard","Order":0,"URL":"/dashboard","Children":[],"UpdatedAt":"2021-05-29T12:46:29.847921-05:00","Status":3,"RecordActions":["validate"],"Deleted":false},{"ID":"CORE","Name":"Core Settings","Description":"Core Settings","Icon":"tune","Order":1,"URL":"","Children":[{"ID":"CORE.NAV","Name":"Navigator","Description":"Navigator","Icon":"vertical_split","Order":0,"URL":"","Children":[],"UpdatedAt":"2021-05-29T12:46:29.849748-05:00","Status":1,"RecordActions":["validate"],"Deleted":false}],"UpdatedAt":"2021-05-29T12:46:29.84899-05:00","Status":3,"RecordActions":["validate"],"Deleted":false}]
