###
# @name authenticate
POST {{app-host}}/api/public/foundation/account/login
Content-Type: application/json

{
    "Password": "{{env-password}}",
    "User": "{{env-user}}"
}


###
# @name Signup
POST {{app-host}}/api/public/foundation/account/signup
Content-Type: application/json

{
    "Name": "phoenix",
    "MiddleName": "phoenix",
    "LastName": "phoenix",
    "Email": "phoenix@gmail.com",
    "Username": "phoenix",
    "Password": "phoenix"
}

