
### GoDataType
# @name authenticate
POST {{app-host}}/api/public/foundation/account/login
Content-Type: application/json

{
    "Password": "{{env-password}}",
    "User": "{{env-user}}"
}

@Authorization = Bearer {{authenticate.response.body.$.JWT}}

#############################################################

###
# @name LIST_ACTIVE_NavElementss
GET {{app-host}}/api/foundation/navigator/elements/active-records/role/ADM_GRL
Content-Type: application/json
Authorization: {{Authorization}}




###############################################################
###############################################################
# @name GET_BY_ID_NavElements
GET {{app-host}}/api/foundation/navigator/elements/element/MAIL
Content-Type: application/json
Authorization: {{Authorization}}

###
@ID = MAIL
@UpdatedAt = {{GET_BY_ID_NavElements.response.body.$.UpdatedAt}}

###
# @name INSERT_NavElements
POST {{app-host}}/api/foundation/navigator/elements/element
Content-Type: application/json
Authorization: {{Authorization}}

{
    "ID": "MAIL.X",
    "Name": "Mail X",
    "Description": "Mail X Templates",
    "Icon": "mail",
    "Order": 0,
    "URL": "#",
    "ParentID": "MAIL"
}


###
# @name EDIT_NavElements
PUT  {{app-host}}/api/foundation/navigator/elements/element
Content-Type: application/json
Authorization: {{Authorization}}

{
    "ID": "{{ID}}",
    "Name": "Mail",
    "Description": "Mail Templates.",
    "Icon": "mail",
    "Order": 0,
    "URL": "#",
    "Parent": "",
    "UpdatedAt": "{{UpdatedAt}}"
}


###
# @name VALIDATE_NavElements
PUT  {{app-host}}/api/foundation/navigator/elements/element/validate
Content-Type: application/json
Authorization: {{Authorization}}

{
    "ID": "{{ID}}",
    "UpdatedAt": "{{UpdatedAt}}"
}


###
# @name INVALIDATE_NavElements
PUT  {{app-host}}/api/foundation/navigator/elements/element/invalidate
Content-Type: application/json
Authorization: {{Authorization}}

{
    "ID": "{{ID}}",
    "UpdatedAt": "{{UpdatedAt}}"
}

###
# @name SOFT_DELETE_NavElements
PUT  {{app-host}}/api/foundation/navigator/elements/element/soft-delete
Content-Type: application/json
Authorization: {{Authorization}}

{
    "ID": "{{ID}}",
    "UpdatedAt": "{{UpdatedAt}}"
}

###
# @name HARD_DELETE_NavElements
PUT  {{app-host}}/api/foundation/navigator/elements/element/hard-delete
Content-Type: application/json
Authorization: {{Authorization}}

{
    "ID": "{{ID}}",
    "UpdatedAt": "{{UpdatedAt}}"
}



###
# @name ASSOCIATE_ROLE_NavElements
PUT  {{app-host}}/api/foundation/navigator/elements/element/associate-role
Content-Type: application/json
Authorization: {{Authorization}}

{
    "NavElementID": "MAIL.X",
    "RoleID": "ADM_GRL"
}



###
# @name DISSOCIATE_ROLE_NavElements
PUT  {{app-host}}/api/foundation/navigator/elements/element/dissociate-role
Content-Type: application/json
Authorization: {{Authorization}}

{
    "NavElementID": "MAIL.X",
    "RoleID": "ADM_GRL"
}
