###
# @name authenticate
POST {{app-host}}/api/public/foundation/account/login
Content-Type: application/json

{
    "Password": "{{env-password}}",
    "User": "{{env-user}}"
}

@Authorization = Bearer {{authenticate.response.body.$.JWT}}

#############################################################

###
# @name get_navigators
GET {{app-host}}/api/foundation/navigators
Content-Type: application/json
Authorization: {{Authorization}}

{
    "limit": 1,
    "offset": 2,
    "sort": ["+Name"],
    "filter":{
        "$and":[
            {"Name":{"$nilike":"something%"}},
            {"Icon":"hey"}
        ]
    }
}