
### GoDataType
# @name authenticate
POST {{app-host}}/api/public/foundation/account/login
Content-Type: application/json

{
    "Password": "{{env-password}}",
    "User": "{{env-user}}"
}

@Authorization = Bearer {{authenticate.response.body.$.JWT}}

#############################################################

###
# @name LIST_ALL_Modules
GET {{app-host}}/api/foundation/modules
Content-Type: application/json
Authorization: {{Authorization}}

###
# @name LIST_ACTIVE_Modules
GET {{app-host}}/api/foundation/modules/active-records
Content-Type: application/json
Authorization: {{Authorization}}

###
# @name LIST_FILTERED_Modules
POST {{app-host}}/api/foundation/modules
Content-Type: application/json
Authorization: {{Authorization}}

{
    "limit": 0,
    "offset": 0,
    "sort": ["+ID","+Name","+Description","+Order","+ParentID","+CreatedAt","+UpdatedAt",
    ]
}



###############################################################
###############################################################
# @name GET_BY_ID_Module
GET {{app-host}}/api/foundation/modules/module/:id/
Content-Type: application/json
Authorization: {{Authorization}}

###
@ID = {{GET_BY_ID_Module.response.body.$.ID}}
@UpdatedAt = {{GET_BY_ID_Module.response.body.$.UpdatedAt}}

###
# @name INSERT_Module
POST {{app-host}}/api/foundation/modules/module
Content-Type: application/json
Authorization: {{Authorization}}

{
    "Name": "",
    "Description": "",
    "Order": 0,
    "ParentID": "",
}


###
# @name EDIT_Module
PUT  {{app-host}}/api/foundation/modules/module
Content-Type: application/json
Authorization: {{Authorization}}

{
    "ID": "{{ID}}",
    "Name": "",
    "Description": "",
    "Order": 0,
    "ParentID": "",
    "UpdatedAt": "{{UpdatedAt}}",
}


###
# @name VALIDATE_Module
PUT  {{app-host}}/api/foundation/modules/module/validate
Content-Type: application/json
Authorization: {{Authorization}}

{
    "ID": "{{ID}}",
    "UpdatedAt": "{{UpdatedAt}}",
}


###
# @name INVALIDATE_Module
PUT  {{app-host}}/api/foundation/modules/module/invalidate
Content-Type: application/json
Authorization: {{Authorization}}

{
    "ID": "{{ID}}",
    "UpdatedAt": "{{UpdatedAt}}",
}

###
# @name SOFT-DELETE_Module
PUT  {{app-host}}/api/foundation/modules/module/soft-delete
Content-Type: application/json
Authorization: {{Authorization}}

{
    "ID": "{{ID}}",
    "UpdatedAt": "{{UpdatedAt}}",
}

###
# @name HARD-DELETE_Module
PUT  {{app-host}}/api/foundation/modules/module/hard-delete
Content-Type: application/json
Authorization: {{Authorization}}

{
    "ID": "{{ID}}",
    "UpdatedAt": "{{UpdatedAt}}",
}
