
### GoDataType
# @name authenticate
POST {{app-host}}/api/public/foundation/account/login
Content-Type: application/json

{
    "Password": "{{env-password}}",
    "User": "{{env-user}}"
}

@Authorization = Bearer {{authenticate.response.body.$.JWT}}

#############################################################

###
# @name LIST_ALL_Navigators
GET {{app-host}}/api/foundation/navigators
Content-Type: application/json
Authorization: {{Authorization}}

###
# @name LIST_ACTIVE_Navigators
GET {{app-host}}/api/foundation/navigators/active-records
Content-Type: application/json
Authorization: {{Authorization}}

###
# @name LIST_FILTERED_Navigators
POST {{app-host}}/api/foundation/navigators
Content-Type: application/json
Authorization: {{Authorization}}

{
    "limit": 0,
    "offset": 0,
    "sort": ["+ID","+Name","+Description","+Icon","+Order","+URL","+Parent","+CreatedAt","+UpdatedAt"
    ]
}



###############################################################
###############################################################
# @name GET_BY_ID_Navigator
GET {{app-host}}/api/foundation/navigators/navigator/MAIL
Content-Type: application/json
Authorization: {{Authorization}}

###
@ID = MAIL
@UpdatedAt = {{GET_BY_ID_Navigator.response.body.$.UpdatedAt}}

###
# @name INSERT_Navigator
POST {{app-host}}/api/foundation/navigators/navigator
Content-Type: application/json
Authorization: {{Authorization}}

{
    "ID": "MAIL",
    "Name": "Mail",
    "Description": "Mail Templates",
    "Icon": "mail",
    "Order": 0,
    "URL": "#",
    "ParentID": ""
}


###
# @name EDIT_Navigator
PUT  {{app-host}}/api/foundation/navigators/navigator
Content-Type: application/json
Authorization: {{Authorization}}

{
    "ID": "{{ID}}",
    "Name": "Mail",
    "Description": "Mail Templates.",
    "Icon": "mail",
    "Order": 0,
    "URL": "#",
    "Parent": "",
    "UpdatedAt": "{{UpdatedAt}}"
}


###
# @name VALIDATE_Navigator
PUT  {{app-host}}/api/foundation/navigators/navigator/validate
Content-Type: application/json
Authorization: {{Authorization}}

{
    "ID": "{{ID}}",
    "UpdatedAt": "{{UpdatedAt}}"
}


###
# @name INVALIDATE_Navigator
PUT  {{app-host}}/api/foundation/navigators/navigator/invalidate
Content-Type: application/json
Authorization: {{Authorization}}

{
    "ID": "{{ID}}",
    "UpdatedAt": "{{UpdatedAt}}"
}

###
# @name SOFT-DELETE_Navigator
PUT  {{app-host}}/api/foundation/navigators/navigator/soft-delete
Content-Type: application/json
Authorization: {{Authorization}}

{
    "ID": "{{ID}}",
    "UpdatedAt": "{{UpdatedAt}}"
}

###
# @name HARD-DELETE_Navigator
PUT  {{app-host}}/api/foundation/navigators/navigator/hard-delete
Content-Type: application/json
Authorization: {{Authorization}}

{
    "ID": "{{ID}}",
    "UpdatedAt": "{{UpdatedAt}}"
}
